inherit_from: .rubocop_todo.yml
AllCops:
  Exclude:
    - 'bin/**/*' # I didn't write these, so I don't want to touch them.
    - 'vendor/**/*' # Travis puts stuff here.
Style/StringLiterals:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
