# Case-insensitive substring on the left,
# replacement on the right.
# Final line is a fall-through.

!omap
  Call-in: Call-in
  Callin: Call-in
  Call in: Call-in
  Children: Children’s
  Debate: Debate
  Documentary: Documentary
  Drama: Drama
  Event Coverage: Event Coverage
  Fundraiser: Fundraiser
  Pledge: Fundraiser
  Game Show: Game Show
  Quiz Show: Game Show
  Instructional: Instructional
  How to: Instructional
  How-to: Instructional
  Interview: Interview
  Magazine: Magazine
  Mini: Miniseries
  News Report: News Report
  Performance: Performance
  Promo: Promo
  Public Service Announcement: Public Service Announcement
  PSA: Public Service Announcement
  Radio Theater: Radio Theater
  Special: Special
  Stand-up: Stand-up
  Talk: Talk Show
  Unedited: Unedited
  Raw Footage: Unedited
  '': ''