# Quotes are optional, unless the string contains colons.
# If the image is sitting in the expected place on the media server,
# "thumbnail_url" can be omitted.

- id: cpb-aacip_106-55m90bjp
  org_name: Cincinnati Public Radio
  name: "Interview with Erich Leinsdorf"
  thumbnail_url: /thumbs/audio-digitized.jpg
  
- id: cpb-aacip_204-4302vbmg
  org_name: KWSO
  name: "Warm Springs Program: Sovereignty Statement"
  thumbnail_url: /thumbs/audio-digitized.jpg
  
- id: cpb-aacip_116-37hqc2ws
  org_name: KDLG
  name: "Neighbors: Dennis Lodge"
  thumbnail_url: /thumbs/audio-digitized.jpg
  
- id: cpb-aacip_187-72p5hz05
  org_name: New Hampshire Public Radio
  name: "Perspectives: Vivian Paley"
  thumbnail_url: /thumbs/audio-digitized.jpg
  
- id: cpb-aacip_305-34sj3z88
  org_name: New England Public Radio
  name: "Ayn Rand Lecture on 'A Nation's Unity'"
  thumbnail_url: /thumbs/audio-digitized.jpg
  
- id: cpb-aacip_345-25k98vzs
  org_name: WUMB
  name: "Black Perspectives: Urban Scholar Program"
  thumbnail_url: /thumbs/audio-digitized.jpg
  
- id: cpb-aacip_304-29p2nthd
  org_name: WUSF
  name: "University Beat"
  thumbnail_url: /thumbs/audio-digitized.jpg
  
- id: cpb-aacip_331-010p2nnm
  org_name: WTIP
  name: "Northern Gardening with Diane Booth"
  thumbnail_url: /thumbs/audio-digitized.jpg
  
- id: cpb-aacip_206-90rr56ng
  org_name: Koahnic Broadcasting Corporation
  name: "National Native News: American Indian Dance Theatre"
  thumbnail_url: /thumbs/audio-digitized.jpg
  
- id: cpb-aacip_28-kw57d2qp45
  org_name: Pacifica Radio Archives
  name: "Commentary of a Black Southern Bus Rider / Rosa Parks"
  thumbnail_url: /thumbs/audio-digitized.jpg
  
- id: cpb-aacip_30-9351d435
  org_name: Wisconsin Public Radio
  name: "Inaugural FM Program"
  thumbnail_url: /thumbs/audio-digitized.jpg
  
- id: cpb-aacip_398-61djhhq3
  org_name: Connecticut Public Broadcasting Network
  name: "Connecticut Lawmakers"
  
- id: cpb-aacip_235-870vv6wr
  org_name: KAKM Alaska Public Media
  name: "Running"
  
- id: cpb-aacip_83-07tmppkk
  org_name: KUED
  name: "Civic Dialogue: Health Care Crisis"
  
- id: cpb-aacip_17-386hfkfs
  org_name: Louisiana Public Broadcasting
  name: "Louisiana: The State We're In: Farmers in America"
  
- id: cpb-aacip_245-41zcrqtf
  org_name: Maine Public Broadcasting Network
  name: "Woods and Waters: Bill Arata"
  
- id: cpb-aacip_394-15p8d15f
  org_name: Maryland Public Television
  name: "Newsnight Maryland: AIDS in Maryland"
  
- id: cpb-aacip_153-9673ngtv
  org_name: Oregon Public Broadcasting
  name: "Seven Days: Wind Power"
  
- id: cpb-aacip_129-74cnpgz0
  org_name: UNC-TV
  name: "North Carolina Now"
  
- id: cpb-aacip_23-74cnpdc5
  org_name: WCTE
  name: "Forum 22"
  
- id: cpb-aacip_322-01bk3jtv
  org_name: WEDU
  name: "WEDU Interview: Jimmy Carter"
  
- id: cpb-aacip_283-881jx3z5
  org_name: KCTS 9
  name: "World Trade: The Seattle Summit"
  
- id: cpb-aacip_114-90dv49m9
  org_name: WGBY
  name: "Making it Here: Sweets"
  
- id: cpb-aacip_29-38jdfsrw
  org_name: Wisconsin Public Television
  name: "Wisconsin Energy Report"
  
- id: cpb-aacip_189-09w0vv3c
  org_name: WXXI Public Broadcasting
  name: "The Rochester I Know: Margaret Baum"
  
- id: cpb-aacip_260-8380gm69
  org_name: Wyoming PBS
  name: "Main Street, Wyoming: Arapaho Language and Culture"
  
- id: cpb-aacip_328-52j6qb23
  org_name: Idaho Public Television
  name: "Idaho Reports: Gary Hart and Carole King"
  
- id: cpb-aacip_384-72b8h347
  org_name: KCPT
  name: "1998 Kansas Governor's Debate: The Race Is On"
  
- id: cpb-aacip_221-053ffh76
  org_name: KOCE
  name: "Voter's Pipeline: Vietnam Refugees in Orange County"
  
- id: cpb-aacip_378-51hhmncc
  org_name: Southern Oregon Public Television
  name: "Downstate Gazette: Elk Creek Special"
  
- id: cpb-aacip_46-1937pz42
  org_name: Vermont Public Television
  name: "Points North: Lake Champlain"
  
- id: cpb-aacip_81-59c5b5nr
  org_name: WNED
  name: "Woman: Black Woman"
  
- id: cpb-aacip_15-80ht7n4v
  org_name: WGBH
  name: "The Press and the People: The Responsibilities of Television"
